import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  weight: ['400','500','600','700']
});


export const metadata: Metadata = {
  title: "Grainly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolage.className} h-full antialiased`}
    >
      <body className="min-h-full bg-[#F3F3F2]/30 flex flex-col max-w-200 mx-auto">
        <Navbar/>
        {children}</body>
    </html>
  );
}
